package io.github.architpanigrahi.springbootdsl.feature

enum class SpringFeature {
    WEB_MVC,
    WEB_FLUX,

    DATA_JPA,
    POSTGRES_JDBC,
    MYSQL_JDBC,
    H2_DATABASE,
    DATA_REDIS,
    DATA_MONGODB,
    HTTP_CLIENT_REST,
    HTTP_CLIENT_REACTIVE,

    LOMBOK,
    SPRING_BOOT_ACTUATOR,
    SPRING_SECURITY,
    SECURITY_OAUTH2_CLIENT,
    SECURITY_OAUTH2_RESOURCE_SERVER,
    FLYWAY_MIGRATION,
    LIQUIBASE_MIGRATION,

    SPRING_BOOT_TEST,
}
